apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /   #new
  name: jenkins
  namespace: jenkins
spec:
  rules:
  - host: jenkins.idfctest
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: 8080
